# Generated by Django 5.0.1 on 2024-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.TextField(unique=True)),
                ('pronunciacion', models.CharField(max_length=100)),
                ('traduccion', models.TextField()),
                ('trazos', models.IntegerField()),
            ],
        ),
    ]
