# Generated by Django 5.0.1 on 2024-02-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_a_jp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccion',
            name='orden',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
